#cmakedefine PACKAGE_NAME "@PACKAGE_NAME@"
#cmakedefine PACKAGE_TARNAME "@PACKAGE_TARNAME@"
#cmakedefine PACKAGE_VERSION "@PACKAGE_VERSION@"
#cmakedefine PACKAGE_STRING "@PACKAGE_STRING@"
#cmakedefine PROGRAM_PREFIX "@PROGRAM_PREFIX@"

#cmakedefine HAVE_WIL
#cmakedefine HAVE_DIRECTXMATH
#cmakedefine HAVE_DIRECTXTK12

#cmakedefine HAVE_MS_GSL
#cmakedefine HAVE_CATCH2
#cmakedefine HAVE_FMT
#cmakedefine HAVE_SPDLOG
#cmakedefine HAVE_RAPIDJSON
